
#SIMPLE LINEAR REGRESSION

import numpy as np

import matplotlib.pyplot as plt

import pandas as pd

dataset = pd.read_csv(r'C:\Users\Dell pc\OneDrive\Desktop\Projects\Linear Regression\Salary_Data.csv')

X = dataset.iloc[:, :1].values

#iloc returns a pandas series when one row is selected (:-1 exclude col from right side)

y = dataset.iloc[:,1].values

#: colon will read from first to last column dataset (3 to get the only dependent variale becuase python indexing start from 0)

#SPLITTING DATASET FOR TRAINING AND TESTING

from sklearn.model_selection import train_test_split

#import the train_test_split class from sklearn.model_selection

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# done with data processing part

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

#creation of regressor object for regression class

regressor.fit(X_train, y_train)

#fit the regressor object to our training set & by using this method model will learn automatically
#by using regressor.fit machine able to learn training data using simple linear regression model 
#machine is able to understand the corelation b/w No. of experience vs the salary (X & Y)
#This is most simple machine learning model which we will build or we created 1st machine learning model

#PREDICTING THE TEST RESULT 
#1st step we import the library, 2nd step data has been preprocess
#3rd step import simplelinearregressor to build the machine learning model and model has trained the training phase
#we are tellin to machine to learn the corelation b/w No of yr exper vs salary itself using regressor.fit method 
#Next step we will see how our machine is predict which will for the test set of observation

y_pred = regressor.predict(X_test)

#visualize the training data set

plt.scatter(X_train, y_train, color = 'red')

plt.plot(X_train, y_train, color = 'blue')
plt.title('Salary and Experience (Training Set)')
plt.xlabel('YOE')
plt.ylabel('Salary')
plt.show()

#slope generation

m = regressor.coef_
m

#intercept also generated by model

c = regressor.intercept_ 
c

#predict the future

y_12 = 9312 * 12 + 26780

y_13 = 9312 * 13 + 26780

#to check overfitting (low bias high variance)

bias = regressor.score(X_train, y_train)
bias



#to check under fitting (high bias low variance)

variance = regressor.score(X_test, y_test)
variance


 
 



